version: 2

updates:
- package-ecosystem: "npm"
  directory: '/'
  schedule:
    interval: weekly
    time: '00:00'
  open-pull-requests-limit: 1
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope